<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
</head>
<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
<body>
<img src="https://kpfu.ru//portal/docs/F_1313344075/02_logotip_3_stroki_cvetnoj.png" alt="">
<h1>Ссылка на подтверждение:</h1>
<h2><a href="${server_url}/confirm/${confirm_code}">Пройдите по ссылке</a></h2>
</body>
</html>